name: CI

on:
  push:
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
  schedule:
    - cron: "0 13 * * 1" # 1300 UTC on Mondays
  workflow_dispatch:

jobs:
  test:
    name: Test on ubuntu-latest, Python ${{ matrix.python-version }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a


      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          uv sync --all-extras --frozen

      - name: List versions
        run: |
          uv pip list

      - name: Run tests
        run: |
          uv run pytest -v --cov=gha_runner --cov-report=xml --color=yes .

      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
